---
  - name: create project network
    hosts: 127.0.0.1
    tasks:
      - name: create network
        docker_network: 
          name: mq-network
      - name: run consul container
        docker_container:
          name: mq0-sd
          image: consul:1.7.3 
          ports:
            - "6115:8500"
            - "6116:8600"
      - name: run docker registry container
        docker_container:
          name: mq0-registry
          image: registry
          networks:
            - name: mq0-network
      - name:  run docker swarm master container