---
  - name: create project network
    hosts: 127.0.0.1
    tasks:
      - name: create network
        docker_network: 
          state: present
          name: mq-network
          attachable: yes

      - name: run kafka container
        docker_container:
          name: mq-kafka
          image: zookeeper:3.4.14
          networks:
            -name: mq-network
          ports:
            - "6115:8500"
            - "6116:8600"

      - name: run rabbitmq container
        docker_container:
          name: mq-rabbitmq
          hostname: mq-rabbitmq
          image: rabbitmq:3.8.3-management-alpine
          networks:
            -name: mq-network
          ports:
            - "6116:15672"
          env:
            RABBITMQ_DEFAULT_USER: "admin"
            RABBITMQ_DEFAULT_PASS: "password"

      - name: run redis container
        docker_container:
          name: mq-redis
          image: redis:6.0.1-alpine3.11  
          networks:
            -name: mq-network
          ports:
            - "6117:6379"
          command: redis-server --appendonly yes